### ISSUE TITLE
Error adding interfaces to existing columns with camelCase naming

### ISSUE THREAD

**Issue by fl034** [directus/app#1356]
# Bug Report

## Steps to Reproduce

1. Enable managing of existing MySQL (5.6) table.
2. Try to add interface (e.g. relation or datetime) to a field with a camelCase name
3. Getting error message `Column already exists: 1060 Duplicate column name "myColumnName"`

## Expected Behavior

Being able to use Directus on columns with camel case naming.

## Actual Behavior

UI shows nothing, but error in JS console.

## Other Context & Screenshots

![bildschirmfoto 2019-02-18 um 21 29 17](https://user-images.githubusercontent.com/11268968/52975211-e9c32e00-33c4-11e9-8850-61954a0f8d5b.png)

## Technical Details

- Web Server: [eg: Apache 2.4.37]
- PHP Version: 7.2
- Database: MySQL 5.6 
- Install Method: FTP-Upload of Directus 7.0.17

**Comment by dev7ch** [comment]
@benhaynes and @rijkvanzanten this has been fixed in #1374

**Comment by Mohamed-Hamed** [comment]
Hello,
I have just downloaded the directus suite to use it for an existing database, and I am still having this issue. Column already exists when I try to change the interface of a camel case column.
