### ISSUE TITLE
Error when saving avatar for user

### ISSUE THREAD

**Issue by onlinelessons** [directus/app#1752]
I'm using current version 7.5.0. I'm getting an error when saving an avatar for a user. If I'm creating a new user I don't get any errors, the avatar file gets stored in directus_files but the file id is not saved in directus_users. When I'm updating an existing user and add a new avatar, I'm getting an "internal server error". In the log files I found this:
api[_].ERROR: TypeError: Argument 3 passed to Directus\Database\TableGateway\RelationalTableGateway::recordActivity() must be of the type array, null given, called in /var/www/htdocs/directus/src/core/Directus/Database/TableGateway/RelationalTableGateway.php on line 551 in /var/www/htdocs/directus/src/core/Directus/Database/TableGateway/RelationalTableGateway.php:2300

**Comment by shealavington** [comment]
Cheers for the issue and the error log.

Based on that error and an _"Ongoing Investigation"_ haha, I'm going to go ahead and say it's the same issue as https://github.com/directus/api/issues/1015 and should be resolved soon.

I'll close this issue as there's an ongoing conversation in the linked issue and you can check there for status-updates on this.

**Comment by onlinelessons** [comment]
I updated to v7.6.0 but I still get an "internal server error" when saving an avatar for a user.

**Comment by shealavington** [comment]
Did you update the API too?
