### ISSUE TITLE
Color interface: NULL color suggestion to use different icon instead of black

### ISSUE THREAD

**Issue by JbalTero** [directus/app#1995]
Currently, the default null for color interface is black, I suggest to display is as something like:

![image](https://user-images.githubusercontent.com/3615746/63909861-0072cd80-ca57-11e9-8241-b4e0649a964f.png)

![Annotation 2019-08-29 120940](https://user-images.githubusercontent.com/3615746/63909875-141e3400-ca57-11e9-9f4c-9b8ee62093dd.png)

**Comment by bjgajjar** [comment]
Fixed in #1999

**Comment by JbalTero** [comment]
@bjgajjar tested this and still the same black, this confuses the user.

![image](https://user-images.githubusercontent.com/3615746/63937593-55cdcf80-ca95-11e9-8598-910312205dae.png)

**Comment by bjgajjar** [comment]
Did you take the PULL from [here](https://github.com/directus/app/pull/1999)?
